# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3
loom_version=1.17.17

# Mod Properties
mod_version=9.1.0
maven_group=com.soarclient
archives_base_name=soarclient-fork

# Dependencies
fabric_version=0.141.6+1.21.11
viafabricplus_version=4.4.15
skija_version=0.143.17
